#############################################################
# PowerShell Console Size Configuration Script V.1
# Description: Sets permanent console window size for multiple PowerShell versions
# Author: Generated by Claude
# Date: April 12, 2025
#############################################################

function Set-ConsolePermanentSize {
    # Check for administrative privileges to modify registry
    $IsAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator
    )
    
    # Prevent execution without admin rights
    if (-not $IsAdmin) {
        echo "This operation requires administrative privileges." -fgc Red
        return
    }

    # Alphabetized registry paths for all PowerShell consoles
    $ConsolePaths = @(
        "HKCU:\Console",
        "HKCU:\Console\%SystemRoot%_System32_pwsh.exe",
        "HKCU:\Console\%SystemRoot%_System32_WindowsPowerShell_v1.0_powershell.exe",
        "HKCU:\Console\powershell.exe"
    )
    
    # Define consistent window parameters
    $Width = 100
    $Height = 27
    $FontSize = 20

    # Attempt registry modifications for all console paths
    # Gracefully handles errors to prevent partial configurations
    try {
        # Apply settings across all console paths
        foreach ($ConsolePath in $ConsolePaths) {
            # Create registry path if missing
            if (-not (Test-Path $ConsolePath)) {
                NI -Path $ConsolePath -Force | Out-Null
            }

            # Set window size (bitwise height + width)
            SP -Path $ConsolePath -Name "WindowSize" `
               -Value ([int](($Height -shl 16) + $Width)) -EA 0
            
            # Set scrollable buffer
            SP -Path $ConsolePath -Name "ScreenBufferSize" `
               -Value ([int](($Height * 5 -shl 16) + $Width)) -EA 0
            
            # Configure font
            SP -Path $ConsolePath -Name "FontSize" `
               -Value ([int](($FontSize -shl 16) + $FontSize)) -EA 0
            SP -Path $ConsolePath -Name "FontFamily" -Value 0x00000036 -EA 0
            SP -Path $ConsolePath -Name "FaceName" -Value "Consolas" -EA 0
        }
        
        echo "Console size and font permanently set for PowerShell" -fgc Green
    }
    catch {
        echo "Error setting console size: $_" -FGC Red
    }
}

# Execute configuration
Set-ConsolePermanentSize